---
title: "Julie Thesis Results"
author:
- Julie A. Nadeau
- Douglas A. Campbell
date: "`r format(Sys.Date())`"
output:
  html_document:
    df_print: paged
    code_folding: hide
    keep_md: yes
    fig_caption: yes
    toc: TRUE
    toc_float: TRUE   
csl: plos-one.csl
---

## Results 



## Discussion

Bath_ETR_LRC_Fitting.Rmd

{r LRCplatt_plot, fig.cap = "Light response curves of PSII electron transport (e- PSII-1 s-1) for three *Prochlorococcus* strains after growth under different combinations of light level and oxygen concentration. The green points represent the experimental data, the black line denotes the fitted model (CITATION), and the red points denote residual values.", out.height="800pt", out.width="100%", echo = FALSE}


{r PmaxPlot, fig.cap = "Analysis of Maximum Electron Transport Rate for *Prochlorococcus*. Analyses of maximum photosynthetic rate (Pmax),  derived from light response curve fits (XXXRefer to Figure). Pmax is plotted vs. measurement oxygen concentrations, with error bars representing the standard error of the estimate. Data is grouped by strain and growth light level.", out.height="800pt", out.width="100%", echo = FALSE}

OlisImportCorr.Rmd

{r SecondDerivPlot, Fig cap = "This plot illustrates the spectral data obtained from an OLIS spectrophotometer for strain MED4 under varying oxygen concentrations (O2_uM) and photosynthetically active radiation (PAR_ue) levels.The black lines represent the second derivative spectra at 25 and 250 µM oxygen concentration, while the red lines depict the second derivative spectra at 25 and 250 µM oxygen concentration. ", out.height="800pt", out.width="100%", echo = FALSE}

!!! this one i need explaining of what the lines are !!!


DualPamPlotting.Rmd

{r DualPamLRC, fig.cap = "Light response curves of PSI electron transport (e- PSI-1 s-1) for two *Prochlorococcus* strains after growth under different combinations of light level and oxygen concentration. The blue and red points represent the experimental data.", out.height="800pt", out.width="100%", echo = FALSE}}

In this plot, the red dots represent the parameter "qP" (photochemical quenching), and the blue dots represent the parameter "YI" (Photosystem I).

qP (Photochemical Quenching): This parameter reflects the proportion of active reaction centers within photosystem I (PSI) capable of transferring electrons during the light-dependent reactions of photosynthesis. Higher qP values typically indicate more efficient photochemical activity, meaning more active PSII reaction centers.

YI (photosystem I): YI stands for "Yield of Photosystem I (PSI)." This parameter measures the efficiency of photosystem I (PSI) in capturing and utilizing light energy during photosynthesis.
The observation that the blue dots are present in the plot indicates the relationship between the efficiency of PSI and the photosynthetically active radiation (PAR) levels represented on the x-axis.

So, in summary, the red dots (qP) represent the efficiency of photochemical energy conversion, while the blue dots (YI) represent the yield of photosystem I.

